# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/riann/',
                'doc_host': 'https://daniel-om-weber.github.io',
                'git_url': 'https://github.com/daniel-om-weber/riann',
                'lib_path': 'riann'},
  'syms': { 'riann.riann': { 'riann.riann.RIANN': ('riann.html#riann', 'riann/riann.py'),
                             'riann.riann.RIANN.__init__': ('riann.html#riann.__init__', 'riann/riann.py'),
                             'riann.riann.RIANN.predict': ('riann.html#riann.predict', 'riann/riann.py'),
                             'riann.riann.RIANN.predict_sequence': ('riann.html#riann.predict_sequence', 'riann/riann.py'),
                             'riann.riann.RIANN.predict_step': ('riann.html#riann.predict_step', 'riann/riann.py'),
                             'riann.riann.RIANN.reset_state': ('riann.html#riann.reset_state', 'riann/riann.py'),
                             'riann.riann.RIANN.set_sampling_rate': ('riann.html#riann.set_sampling_rate', 'riann/riann.py')}}}
