# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RIANN": "riann.ipynb"}

modules = ["riann.py"]

doc_url = "https://daniel-om-weber.github.io/riann/"

git_url = "https://github.com/daniel-om-weber/riann/tree/master/"

def custom_doc_links(name): return None
