name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev>=2.0.0 jupyter
        pip install -e .
    - name: Check if all notebooks are cleaned
      run: |
        echo "Check we are starting with clean git checkout"
        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
        echo "Trying to clean notebooks"
        nbdev_clean
        echo "Check that clean was unnecessary"
        git status -s
        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unclean notebooks\n!!!Remember to run nbdev_clean"; false; fi
    - name: Check if there is no diff library/notebooks
      run: |
        nbdev_export
        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected differences between the notebooks and the exported library"; false; fi
    - name: Run tests
      run: |
        nbdev_test